### ISSUE TITLE
Error with terra/aqua awips processing script

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/sandy-utils#14]
Looks like some files can't be found by the Dir.glob that happens @ https://github.com/gina-alaska/sandy-utils/blob/master/bin/terra_and_aqua_awips.rb#L97

Which causes the cp to fail because of a nil option.

**Comment by spruceboy** [comment]
Hum, yeah, that is dumb, it only the 1k bands are made at night, so the other files don't exist.

**Comment by smacfarlane** [comment]
I'd like also address #12 in this pull request.  

It looks like the modis2awips scripts understand the YYJJJ.HHMM  naming convention, so we shouldn't need to be double-renaming things (SeaDAS -> YYmmdd.HHMM -> YYJJJ.HHMM).  

I propose that the l1 script pushes the SeaDAS named files to the cache, and the awips script copies and renames them locally before processing. 

Thoughts?

**Comment by spruceboy** [comment]
Sounds good to me, but I would propose either switching to the YYJJJ.HHMM scheme l1 script , or staying with the SeaDAS naming for the entire way (polar2grid understands that naming as well) 
. 
The seadas naming is the least friendly to read, I would prefer to switch to the YYJJJ.HHMM scheme in the l1 script and staying with it the entire way. 

Sound reasonable?  Should I make and push out that change or do you want to do it @smacfarlane ?

**Comment by smacfarlane** [comment]
@spruceboy  Go ahead and make the change, I probably won't be able to get to it until later in the week.
