### ISSUE TITLE
modis awips generation not saving files

### ISSUE THREAD

**Issue by smacfarlane** [gina-alaska/sandy-utils#18]
@spruceboy 

It looks like the aqua processing isn't matching any files to copy to the cache.  Here's the gist of the latest run.  You can see it generate products successfully, but there are no messages about copying files, and the products list is empty.  

https://gist.github.com/smacfarlane/078820021dc5e764e5f8

**Comment by cfdierking** [comment]
Scott,
Is there a similar problem with Terra?  I haven't seen any data for about
14 hours.
Carl

On Thu, Sep 10, 2015 at 10:40 PM, Scott Macfarlane <notifications@github.com

**Comment by teknofire** [comment]
@spruceboy looks like the config for the save glob only includes terra, need to add the aqua one as well

See: https://github.com/gina-alaska/sandy-utils/blob/master/config/terra_and_aqua_awips.yml#L8-L11

I believe it needs to have the equivalent `"UAF_AWIPS_aqua_modis_vis0[123467]*"` entries added

**Comment by spruceboy** [comment]
Yup, looks like I forget to expand the globs.  Will fix in a second and issue a pull request with the fix.
