### ISSUE TITLE
shell_out! process status should propagate out

### ISSUE THREAD

**Issue by smacfarlane** [gina-alaska/sandy-utils#34]
Currently, an non-zero exist status on shell_out! isn't always caught.  This can allow a command to fail to run, but the script will still exit 0.  This causes problems in automation when that exit code is the only indicator of success/failure.

**Comment by spruceboy** [comment]
maybe shell_out should throw an exception  on non-zero exit status.  Are there any situations were  a shelled out command is returning non-zero but still working, in the context of these processing tools?

**Comment by teknofire** [comment]
`shell_out!` now throws exceptions on non-zero exit, `shell_out` maintains the previous behavior but prints a message when the process has a non-zero exit status
